export const TRACKS = [
  {
    id: 1,
    src: './assets/audio/1.Machinegun_-_Scream_Inc.mp3',
    image: './assets/images/1.jpg',
    background: './assets/images/back.jpg',
    duration: '03:06',
    artist: 'Scream Inc.',
    name: 'Machinegun',
  },
  {
    id: 2,
    src: './assets/audio/2.Hands_of_Attrition_-_Solace.mp3',
    image: './assets/images/2.jpg',
    background: './assets/images/22.jpg',
    duration: '06:00',
    artist: 'Hands of Attrition',
    name: 'Solace',
  },
  {
    id: 3,
    src: './assets/audio/3.Metal_Child_-_Avenger_Kills.mp3',
    image: './assets/images/3.jpg',
    background: './assets/images/33.webp',
    duration: '04:35',
    artist: 'Avenger Kills',
    name: 'Metal Child',
  },
  {
    id: 4,
    src: './assets/audio/4.Road_-_Kolony.mp3',
    image: './assets/images/4.jpg',
    background: './assets/images/44.jpg',
    duration: '04:35',
    artist: 'Kolony',
    name: 'Road',
  },
  {
    id: 5,
    src: './assets/audio/5.Wake_Up_-_One_missed_may.mp3',
    image: './assets/images/5.jpg',
    background: './assets/images/55.jpg',
    duration: '03:53',
    artist: 'One missed may',
    name: "Wake Up, Don't Lose It",
  },
  {
    id: 6,
    src: './assets/audio/6._Nothing_To_Fear_-_Hide_amp_Dream.mp3',
    image: './assets/images/6.jpg',
    background: './assets/images/66.jpg',
    duration: '03:08',
    artist: 'Hide Dream',
    name: 'Nothing To Fear',
  },
];
